spring:
  application:
    name: caffe
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false
        http-only: true
        max-age: 1800
      timeout: 30m

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
