spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.orm.jdbc.bind: ERROR
    org.hibernate.orm.jdbc.extract: ERROR
    org.springframework.transaction.interceptor: ERROR
    com.back: INFO